# Generated by Django 6.0.4 on 2026-06-04 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Compañía')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País de Origen')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Juego')),
                ('genre', models.CharField(max_length=100, verbose_name='Género')),
                ('platform', models.CharField(max_length=100, verbose_name='Plataforma')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2031)], verbose_name='Año de Lanzamiento')),
                ('description', models.TextField(blank=True, help_text='Breve resumen del juego', verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/', verbose_name='Portada del Juego')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='videogames.company', verbose_name='Desarrolladora')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
                'ordering': ['-release_year'],
            },
        ),
    ]
