# Generated by Django 6.0.4 on 2026-05-15 23:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ['-release_year'], 'verbose_name': 'Videojuego', 'verbose_name_plural': 'Videojuegos'},
        ),
        migrations.AddField(
            model_name='videogame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videogame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='description',
            field=models.TextField(blank=True, help_text='Breve resumen del juego', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.CharField(max_length=100, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2031)], verbose_name='Año de Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del Juego'),
        ),
    ]
