# Generated by Django 6.0.4 on 2026-05-16 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0003_alter_videogame_options_videogame_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Compañía')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País de Origen')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='videogame',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='videogames.company', verbose_name='Desarrolladora'),
        ),
    ]
